[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/", "openzeppelin-contracts/=lib/openzeppelin-contracts/"]
solc_version = "0.8.23"

[fmt]
line_length = 120

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }
